/**
 * Shared types for the Superious / Outlier backend.
 *
 * These types are the lingua-franca passed across the agent graph, the
 * persistence layer, the queue, and the API. Everything else in
 * `src/server/*` is built on top of them.
 */

export type JobStatus = 'queued' | 'researching' | 'screenshotting' | 'writing' | 'done' | 'failed';

export type SourceStatus = 'pending' | 'done' | 'failed';

export interface Job {
  id: string;
  userId: string;
  prompt: string;
  status: JobStatus;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Source {
  id: string;
  jobId: string;
  url: string;
  title: string;
  summary: string;
  domain: string;
  publishedAt: string | null;
  rankScore: number | null;
  screenshotPath: string | null;
  screenshotUrl: string | null;
  capturedAt: string | null;
  status: SourceStatus;
  error: string | null;
}

export interface ScriptSegment {
  order: number;
  heading: string;
  narration: string;
  bRollCues: string[];
  sourceIds: string[];
  durationS: number;
  /**
   * Per-segment verification produced by the fact-check pass that runs
   * after the writer node. Optional — older runs don't carry it.
   */
  verification?: SegmentVerification;
}

/**
 * Outcome of cross-referencing a segment's claims against the captured
 * source manifest.
 *
 * Status semantics:
 *   - `supported`    — at least 2 independent domains back the claim.
 *   - `single-source`— only one source backs the claim; weaker but cite-able.
 *   - `contradicted` — at least one captured source disagrees with the claim.
 *   - `unverified`   — the segment couldn't be verified (e.g. no sources).
 */
export type VerificationStatus = 'supported' | 'single-source' | 'contradicted' | 'unverified';

export interface SegmentVerification {
  status: VerificationStatus;
  /** 0–1 confidence the claim is well-supported. */
  confidence: number;
  supportingSourceIds: string[];
  contradictingSourceIds: string[];
  /** Short, human-readable note shown in the verification badge tooltip. */
  notes: string;
}

export interface Script {
  id: string;
  jobId: string;
  title: string;
  hook: string;
  segments: ScriptSegment[];
  outro: string;
  wordCount: number;
  estimatedDurationS: number;
  createdAt: string;
}

/** Raw search hit returned by a `WebSearchProvider`. */
export interface SearchResult {
  url: string;
  title: string;
  snippet: string;
  domain: string;
  publishedAt: string | null;
  score: number | null;
}

/** Output of the `script_writer` LLM node, before persisting as a `Script`. */
export interface ScriptOutput {
  title: string;
  hook: string;
  segments: ScriptSegment[];
  outro: string;
}

/**
 * Mutable state passed from one agent node to the next.
 *
 * Following the LangGraph convention, every node takes the state in and
 * returns an updated state out — never mutating in place. This makes the
 * pipeline trivially unit-testable and replayable.
 */
export interface AgentState {
  jobId: string;
  userId: string;
  prompt: string;
  queries: string[];
  rawResults: SearchResult[];
  sources: Source[];
  script: ScriptOutput | null;
  errors: string[];
}

/** Public-facing event emitted on the SSE stream. */
export type JobEvent =
  | { type: 'status'; status: JobStatus }
  | { type: 'source'; source: Source }
  | { type: 'script'; script: Script }
  | { type: 'error'; message: string; recoverable: boolean }
  | { type: 'done' };

/**
 * A single alternative for the script's hook (0–30s opening).
 *
 * Variants are generated by re-prompting the script-writer LLM with a
 * different "angle" — data-led, contrarian, narrative, etc. — over the
 * same source manifest, so each alternative remains source-grounded.
 */
export type HookAngle = 'data-led' | 'contrarian' | 'narrative' | 'emotional' | 'question-led';

export interface HookVariant {
  id: string;
  angle: HookAngle;
  text: string;
  /** Sources that back the variant's specific framing. */
  sourceIds: string[];
  /** Estimated read time in seconds at 130 wpm. */
  estimatedDurationS: number;
}

/**
 * YouTube-ready packaging derived from the finished script.
 *
 * Generated post-`script_writer` by re-prompting an LLM with the hook +
 * top sources. Title variants are CTR-oriented; thumbnail concepts are
 * art-direction briefs (subject, framing, on-image text) rather than
 * generated images — image generation is out of scope per the v1.0 PRD.
 */
export interface TitleVariant {
  id: string;
  text: string;
  /** Short justification for why this title might perform. */
  rationale: string;
  charCount: number;
}

export interface ThumbnailConcept {
  id: string;
  /** Primary subject of the image. */
  subject: string;
  /** Framing / composition guidance. */
  framing: string;
  /** Optional 2–4 word text overlay; empty string if none. */
  textOverlay: string;
  /** Color / mood guidance. */
  mood: string;
}

export interface TitleThumbnailPack {
  jobId: string;
  titles: TitleVariant[];
  thumbnails: ThumbnailConcept[];
  generatedAt: string;
}

/**
 * Outcome of a single Recapture cron run, comparing the latest crawl
 * against the previous canonical source manifest for the same job.
 */
export interface RecaptureRun {
  id: string;
  scheduleId: string;
  jobId: string;
  /** Display name for the underlying research topic. */
  topic: string;
  ranAt: string;
  /** Newly discovered sources not in the previous run. */
  newSources: RecaptureSourceRef[];
  /** Sources that returned 404/dead since the previous run. */
  brokenSources: RecaptureSourceRef[];
  /** Claims that newer sources now contradict. */
  contradictedClaims: RecaptureContradiction[];
}

export interface RecaptureSourceRef {
  id: string;
  url: string;
  title: string;
  domain: string;
}

export interface RecaptureContradiction {
  segmentHeading: string;
  /** The original claim, paraphrased. */
  claim: string;
  /** What the newer source says. */
  contradiction: string;
  /** Source that introduced the contradiction. */
  newSourceId: string;
  newSourceDomain: string;
}
