'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import ScriptViewer, { type BRollExportItem } from './ScriptViewer';
import SourcePanel from './SourcePanel';
import BRollPanel from './BRollPanel';
import { Camera, BookOpen, ExternalLink, Loader2, CheckCircle2, AlertCircle } from 'lucide-react';

type RightTab = 'sources' | 'broll';

export default function DualPaneView() {
  const [highlightedSourceId, setHighlightedSourceId] = useState<string | null>(null);
  const [rightTab, setRightTab] = useState<RightTab>('sources');
  const [bRollItems, setBRollItems] = useState<BRollExportItem[]>([]);
  const [gdocsStatus, setGdocsStatus] = useState<
    'idle' | 'exporting' | 'success' | 'error' | 'not_connected'
  >('idle');
  const [gdocsUrl, setGdocsUrl] = useState('');
  const [gdocsError, setGdocsError] = useState('');

  async function handleGoogleDocsExport() {
    const accessToken =
      typeof window !== 'undefined' ? localStorage.getItem('google_access_token') : null;

    if (!accessToken) {
      setGdocsStatus('not_connected');
      return;
    }

    setGdocsStatus('exporting');
    setGdocsError('');

    try {
      // Build markdown content for the script
      const title = 'CRISPR & Cancer: The Gene Editing Revolution';
      const markdownContent = `# ${title}

## Hook
Imagine being told you have cancer — and then, six months later, doctors use a molecular pair of scissors to snip the disease out of your DNA. This isn't science fiction. It happened. And the technology behind it is rewriting the rules of medicine faster than anyone expected.

## What Is CRISPR and How Does It Work?
CRISPR-Cas9 is essentially a bacterial immune system that scientists have repurposed as a precision genome editing tool. The Cas9 protein acts like molecular scissors, guided by a short RNA sequence to a specific location in the DNA strand.

## Key Milestones: From Discovery to Clinical Trials
The CRISPR story accelerates remarkably fast. Jennifer Doudna and Emmanuelle Charpentier published the foundational paper in 2012 — they won the Nobel Prize in Chemistry just eight years later.

## CRISPR in Cancer Treatment: How It Works Clinically
In oncology, CRISPR is being deployed in two main ways. First, ex vivo editing — taking a patient's T-cells, editing them outside the body to better recognize cancer antigens, then reinfusing them.

## Ethical Frameworks: The Lines We Must Not Cross
The power of CRISPR forces urgent ethical questions. Somatic editing — changing genes in a living adult — is broadly accepted when it treats disease.

## Access, Equity, and the $2 Million Problem
Casgevy, the approved CRISPR therapy, is priced at 2.2 million dollars per treatment.

## What Comes Next: The 5-Year Horizon
The next five years will be defined by three developments. First, base editing and prime editing — newer CRISPR variants that make single-letter DNA changes without cutting both strands.

## Outro
CRISPR is not a silver bullet — it is a platform. A set of molecular tools that are improving rapidly, being applied carefully, and generating results that would have been called impossible a decade ago.

---
*Generated by outlier*`;

      // Create Google Doc via REST API
      const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ title }),
      });

      if (!createRes.ok) {
        const errData = await createRes.json();
        if (createRes.status === 401) {
          // Token expired — clear and prompt reconnect
          localStorage.removeItem('google_access_token');
          localStorage.removeItem('google_refresh_token');
          setGdocsStatus('not_connected');
          return;
        }
        throw new Error(errData.error?.message || 'Failed to create Google Doc');
      }

      const docData = await createRes.json();
      const docId = docData.documentId;

      // Insert content via batchUpdate
      const insertRes = await fetch(
        `https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`,
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${accessToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            requests: [
              {
                insertText: {
                  text: markdownContent,
                  endOfSegmentLocation: { segmentId: '' },
                },
              },
            ],
          }),
        }
      );

      if (!insertRes.ok) {
        const errData = await insertRes.json();
        throw new Error(errData.error?.message || 'Failed to insert content');
      }

      const docUrl = `https://docs.google.com/document/d/${docId}/edit`;
      setGdocsUrl(docUrl);
      setGdocsStatus('success');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Export failed. Please try again.';
      setGdocsError(message);
      setGdocsStatus('error');
    }
  }

  return (
    <div className="flex flex-col flex-1 overflow-hidden min-h-0">
      {/* Google Docs Status Banner */}
      {gdocsStatus === 'not_connected' && (
        <div className="flex items-center gap-3 px-6 py-2.5 bg-amber-50 border-b border-amber-200 shrink-0">
          <AlertCircle size={14} strokeWidth={2.25} className="text-amber-600 shrink-0" />
          <p className="text-xs text-amber-700 font-medium flex-1">
            Google Docs is not connected. Connect your account in{' '}
            <Link href="/settings" className="underline font-bold">
              Settings → Integrations
            </Link>{' '}
            or during{' '}
            <Link href="/" className="underline font-bold">
              onboarding
            </Link>
            .
          </p>
          <button
            onClick={() => setGdocsStatus('idle')}
            className="text-amber-600 hover:text-amber-800 text-xs font-bold"
          >
            ✕
          </button>
        </div>
      )}
      {gdocsStatus === 'success' && (
        <div className="flex items-center gap-3 px-6 py-2.5 bg-primary/10 border-b border-primary/20 shrink-0">
          <CheckCircle2 size={14} strokeWidth={2.25} className="text-primary shrink-0" />
          <p className="text-xs text-primary font-medium flex-1">
            Script exported to Google Docs successfully!
          </p>
          <a
            href={gdocsUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1 text-xs font-bold text-primary hover:underline"
          >
            Open Doc <ExternalLink size={11} strokeWidth={2.25} />
          </a>
          <button
            onClick={() => setGdocsStatus('idle')}
            className="text-primary hover:opacity-70 text-xs font-bold ml-2"
          >
            ✕
          </button>
        </div>
      )}
      {gdocsStatus === 'error' && (
        <div className="flex items-center gap-3 px-6 py-2.5 bg-red-50 border-b border-red-200 shrink-0">
          <AlertCircle size={14} strokeWidth={2.25} className="text-red-500 shrink-0" />
          <p className="text-xs text-red-600 font-medium flex-1">{gdocsError}</p>
          <button
            onClick={() => setGdocsStatus('idle')}
            className="text-red-500 hover:text-red-700 text-xs font-bold"
          >
            ✕
          </button>
        </div>
      )}
      {gdocsStatus === 'exporting' && (
        <div className="flex items-center gap-3 px-6 py-2.5 bg-muted border-b border-border shrink-0">
          <Loader2 size={14} strokeWidth={2.25} className="text-primary animate-spin shrink-0" />
          <p className="text-xs text-muted-foreground font-medium">Exporting to Google Docs…</p>
        </div>
      )}

      <div className="flex flex-1 overflow-hidden min-h-0">
        {/* Left Pane — Script Viewer */}
        <div className="flex-1 overflow-y-auto scrollbar-thin border-r border-border min-w-0">
          <ScriptViewer
            highlightedSourceId={highlightedSourceId}
            onCitationClick={setHighlightedSourceId}
            onBRollDataReady={setBRollItems}
            onExportGoogleDocs={handleGoogleDocsExport}
          />
        </div>

        {/* Right Pane — Tabbed Panel */}
        <div className="w-[380px] xl:w-[420px] 2xl:w-[460px] shrink-0 flex flex-col overflow-hidden">
          {/* Tab Bar */}
          <div className="flex items-center border-b border-border shrink-0 bg-background">
            <button
              onClick={() => setRightTab('sources')}
              className={`
                flex items-center gap-1.5 px-4 py-3 text-xs font-semibold border-b-2 transition-all duration-150
                ${
                  rightTab === 'sources'
                    ? 'border-primary text-primary'
                    : 'border-transparent text-muted-foreground hover:text-foreground'
                }
              `}
            >
              <BookOpen size={13} />
              Sources
            </button>
            <button
              onClick={() => setRightTab('broll')}
              className={`
                flex items-center gap-1.5 px-4 py-3 text-xs font-semibold border-b-2 transition-all duration-150
                ${
                  rightTab === 'broll'
                    ? 'border-primary text-primary'
                    : 'border-transparent text-muted-foreground hover:text-foreground'
                }
              `}
            >
              <Camera size={13} />
              B-Roll
              {bRollItems.length > 0 && (
                <span className="ml-1 font-mono text-2xs bg-muted px-1.5 py-0.5 rounded-full tabular-nums">
                  {bRollItems.length}
                </span>
              )}
            </button>
          </div>

          {/* Tab Content */}
          <div className="flex-1 overflow-y-auto scrollbar-thin">
            {rightTab === 'sources' && (
              <SourcePanel
                highlightedSourceId={highlightedSourceId}
                onSourceClick={setHighlightedSourceId}
              />
            )}
            {rightTab === 'broll' && <BRollPanel items={bRollItems} />}
          </div>
        </div>
      </div>
    </div>
  );
}
