'use client';

import React from 'react';
import AppLayout from '@/components/AppLayout';
import { Clock3, FileText, Sparkles } from 'lucide-react';

const MOCK_ARTIFACTS = [
  { id: 'art-1', title: 'Netflix Streaming Trends 2024', type: 'Script Draft', date: '2024-03-20' },
  { id: 'art-2', title: 'AI Chip Architecture Analysis', type: 'Research PDF', date: '2024-03-19' },
  { id: 'art-3', title: 'SpaceX Starship Progress Report', type: 'Data Table', date: '2024-03-18' },
];

export default function ArtifactPage() {
  return (
    <AppLayout>
      <div className="mx-auto w-full max-w-[1300px] px-8 py-8">
        <div className="min-h-[600px] rounded-[12px] border border-[#ebedf2] bg-white p-10 pt-6">
          <header className="mb-8">
            <div className="mb-2 inline-flex items-center gap-2 rounded-[6px] bg-[#f2f3f6] px-2 py-1 text-[11px] font-semibold text-muted-foreground">
              <Sparkles size={12} />
              GENERATED OUTPUTS
            </div>
            <h1 className="text-[28px] font-bold tracking-tight text-foreground">Artifacts</h1>
            <p className="mt-1 text-xs text-muted-foreground">
              Scripts, source packs, and exports generated by each run.
            </p>
          </header>

          <div className="space-y-3">
            {MOCK_ARTIFACTS.map((artifact) => (
              <article
                key={artifact.id}
                className="group flex items-center justify-between rounded-[8px] border border-[#eceff4] bg-[#fafafa] px-4 py-3 transition-colors duration-150 hover:bg-[#f5f6f9]"
              >
                <div className="flex items-center gap-3">
                  <div className="rounded-[8px] bg-white p-2 text-muted-foreground ring-1 ring-[#eceff4]">
                    <FileText size={18} />
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold text-foreground">{artifact.title}</h3>
                    <p className="mt-0.5 text-xs text-muted-foreground">{artifact.type}</p>
                  </div>
                </div>
                <div className="inline-flex items-center gap-1 rounded-[6px] bg-[#f2f3f6] px-2.5 py-1 text-[11px] font-medium text-muted-foreground">
                  <Clock3 size={12} />
                  {artifact.date}
                </div>
              </article>
            ))}
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
